//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notifications.WSFSOC
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContextBusiness", Namespace="http://schemas.datacontract.org/2004/07/SOC.Svc.WCF.BusinessEntities.Notification" +
        "sApp")]
    public partial class ContextBusiness : object
    {
        
        private string ApplicationField;
        
        private string ClientEmailField;
        
        private string ClientIdentifierField;
        
        private string ClientMobileField;
        
        private string ContractField;
        
        private string ProcessField;
        
        private Notifications.WSFSOC.NotificationTemplate TemplateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Application
        {
            get
            {
                return this.ApplicationField;
            }
            set
            {
                this.ApplicationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientEmail
        {
            get
            {
                return this.ClientEmailField;
            }
            set
            {
                this.ClientEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientIdentifier
        {
            get
            {
                return this.ClientIdentifierField;
            }
            set
            {
                this.ClientIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientMobile
        {
            get
            {
                return this.ClientMobileField;
            }
            set
            {
                this.ClientMobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contract
        {
            get
            {
                return this.ContractField;
            }
            set
            {
                this.ContractField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Process
        {
            get
            {
                return this.ProcessField;
            }
            set
            {
                this.ProcessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notifications.WSFSOC.NotificationTemplate Template
        {
            get
            {
                return this.TemplateField;
            }
            set
            {
                this.TemplateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationTemplate", Namespace="http://schemas.datacontract.org/2004/07/SOC.Svc.WCF.BusinessEntities.Notification" +
        "sApp")]
    public enum NotificationTemplate : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_de_baja_corporativa = 222,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Solvencia_PIN_OTP = 268,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Operacion_Bienvenida_Correo = 272,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Operacions_Bienvenida_Correo = 276,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreBaja_espera_documentacion = 293,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreBaja_Validacion_documentos = 294,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreBaja_Documentacion_Validada = 296,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreBaja_Carta_Recibida = 297,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Prebaja_Carta_Aceptada = 298,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreBaja_Rechazo_Documentacion = 299,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreBaja_Cancelada = 300,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificaciones_Aportaciones_CORP = 307,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMAIL_SOLICITUD_DE_RETIRO_CLIENTE_CORP = 308,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_Cambio_Password = 310,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_Cambio_Datos = 312,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cumpleaños_segmento_A = 314,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cumpleaños_segmento_A_plus = 315,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cumpleaños_segmento_B_mayor_30 = 316,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cumpleaños_segmento_B_menor_30 = 317,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SolvCorp_Notificacion_Reseteo_Contrasena = 318,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cumpleaños_segmento_C_menor_30 = 319,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SolvCorp_Alta_de_administrador_corporativo = 323,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SolvCorp_Modificacion_de_administrador_corporativo = 324,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SolvCorp_Modificacion_admon_corporativo_soporte = 325,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SolvCorp_Baja_Administrador_corporativo = 326,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SolvCorp_Actualizacion_Inf_seguridad = 327,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SolvCorp_Conexion_dispositivo_distinto = 328,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SolvCorp_Bloqueo_dispositivo_usuario = 329,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOTIFICACIONES_RESERVAS_WEALTH = 437,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SolvCorp_Bloqueo_dispositivo_nodo = 1328,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SolvCorp_Envio_de_credenciales_admin_ext = 1330,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SolvCorp_Solicitud_credenciales_corp = 1331,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_Baja_Masiva = 1356,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMAIL_SOLICITUD_AGENTE_DOC_PENDIENTE_CANCELACION = 1364,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMAIL_AGENTE_DOC_PENDIENTE = 1365,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMAIL_SOLICITUD_AGENTE_DOC_PENDIENTE = 1366,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_Baja_Masiva_Error = 1368,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_Baja_Masiva_Vacio = 1369,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_Cambio_Perfil = 1370,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_Retiro_SIIF_AIVA = 1371,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_Pago_Prima_Reporte = 1374,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Confirmar_Transacción_EasyCorp = 1387,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contrato_Aniversario_Single_Premium = 1423,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contrato_Aniversario_Capital_Seguro = 1424,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contrato_Aniversario_Aportaciones_Regulares = 1425,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Retiro_Total_Deposito = 1462,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Retiro_Total_Migracion = 1464,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Welkome_Kit_RS = 1466,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Welkome_Kit_SP = 1467,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_Devolucion_Money_Out = 1484,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Resteo_password_participantes = 1486,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_alta_datos_portalcorp_linea = 1493,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_alta_datos_portalcorp_lineaBR = 1494,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_recuperacion_de_contrasena = 1497,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_Baja_Administrador_Externo_Corp = 1498,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_Cambio_Contrasena = 1499,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_Bloqueo_Usuario = 1500,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Baja_DocOnline = 1503,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Alta_DocOnline = 1504,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_Contratacion_SeguroCare = 1510,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_PIN_Dinamico_Mail = 1511,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_PIN_Dinamico_SMS = 1512,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_Transferencia_Fondos_Corp = 1515,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_Cancelacion_SeguroCare = 1516,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_PIN_Dinamico_Mail_Vinculacion_Digital = 1522,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_Actualizacion_Correo_Retail = 1533,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendParameters", Namespace="http://schemas.datacontract.org/2004/07/SOC.Svc.WCF.BusinessEntities.Notification" +
        "sApp")]
    public partial class SendParameters : object
    {
        
        private System.Collections.Generic.Dictionary<string, string> AdditionalMessagesField;
        
        private decimal AmountField;
        
        private string ClientIdentifierField;
        
        private string ClientTypeIdField;
        
        private string ContractField;
        
        private string EmailClientField;
        
        private string EmailFPField;
        
        private string MobileClientField;
        
        private string MobileFPField;
        
        private Notifications.WSFSOC.NotificationTemplate OperationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> AdditionalMessages
        {
            get
            {
                return this.AdditionalMessagesField;
            }
            set
            {
                this.AdditionalMessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientIdentifier
        {
            get
            {
                return this.ClientIdentifierField;
            }
            set
            {
                this.ClientIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientTypeId
        {
            get
            {
                return this.ClientTypeIdField;
            }
            set
            {
                this.ClientTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contract
        {
            get
            {
                return this.ContractField;
            }
            set
            {
                this.ContractField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailClient
        {
            get
            {
                return this.EmailClientField;
            }
            set
            {
                this.EmailClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailFP
        {
            get
            {
                return this.EmailFPField;
            }
            set
            {
                this.EmailFPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileClient
        {
            get
            {
                return this.MobileClientField;
            }
            set
            {
                this.MobileClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileFP
        {
            get
            {
                return this.MobileFPField;
            }
            set
            {
                this.MobileFPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notifications.WSFSOC.NotificationTemplate Operation
        {
            get
            {
                return this.OperationField;
            }
            set
            {
                this.OperationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/SOC.Svc.WCF.BusinessEntities.BusinessComm" +
        "on")]
    public partial class OperationResult : object
    {
        
        private bool SuccessfulField;
        
        private Notifications.WSFSOC.SystemMessage[] SystemMessagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Successful
        {
            get
            {
                return this.SuccessfulField;
            }
            set
            {
                this.SuccessfulField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notifications.WSFSOC.SystemMessage[] SystemMessages
        {
            get
            {
                return this.SystemMessagesField;
            }
            set
            {
                this.SystemMessagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemMessage", Namespace="http://schemas.datacontract.org/2004/07/SOC.Svc.WCF.BusinessEntities.BusinessComm" +
        "on")]
    public partial class SystemMessage : Notifications.WSFSOC.CatalogEntity
    {
        
        private string MessageField;
        
        private Notifications.WSFSOC.SystemMessageTypes MessageTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notifications.WSFSOC.SystemMessageTypes MessageType
        {
            get
            {
                return this.MessageTypeField;
            }
            set
            {
                this.MessageTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogEntity", Namespace="http://skandia.com.mx/soc/services/2010/07")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notifications.WSFSOC.SystemMessage))]
    public partial class CatalogEntity : object
    {
        
        private string IdentifierField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Identifier
        {
            get
            {
                return this.IdentifierField;
            }
            set
            {
                this.IdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemMessageTypes", Namespace="http://schemas.datacontract.org/2004/07/SOC.Svc.WCF.BusinessEntities.BusinessComm" +
        "on")]
    public enum SystemMessageTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContextBusinessN", Namespace="http://schemas.datacontract.org/2004/07/SOC.Svc.WCF.BusinessEntities.Notification" +
        "sAppN")]
    public partial class ContextBusinessN : object
    {
        
        private string ApplicationField;
        
        private string ClientEmailField;
        
        private string ClientIdentifierField;
        
        private string ClientMobileField;
        
        private string ContractField;
        
        private string ProcessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Application
        {
            get
            {
                return this.ApplicationField;
            }
            set
            {
                this.ApplicationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientEmail
        {
            get
            {
                return this.ClientEmailField;
            }
            set
            {
                this.ClientEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientIdentifier
        {
            get
            {
                return this.ClientIdentifierField;
            }
            set
            {
                this.ClientIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientMobile
        {
            get
            {
                return this.ClientMobileField;
            }
            set
            {
                this.ClientMobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contract
        {
            get
            {
                return this.ContractField;
            }
            set
            {
                this.ContractField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Process
        {
            get
            {
                return this.ProcessField;
            }
            set
            {
                this.ProcessField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationTemplateN", Namespace="http://schemas.datacontract.org/2004/07/SOC.Svc.WCF.BusinessEntities.Notification" +
        "sAppN")]
    public enum NotificationTemplateN : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notificacion_Actualizacion_Correo_Retail = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Solvencia_Pin_OTP = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendParametersN", Namespace="http://schemas.datacontract.org/2004/07/SOC.Svc.WCF.BusinessEntities.Notification" +
        "sAppN")]
    public partial class SendParametersN : object
    {
        
        private System.Collections.Generic.Dictionary<string, string> AdditionalMessagesField;
        
        private decimal AmountField;
        
        private string ClientIdentifierField;
        
        private string ClientTypeIdField;
        
        private string ContractField;
        
        private string EmailClientField;
        
        private string EmailFPField;
        
        private string MobileClientField;
        
        private string MobileFPField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> AdditionalMessages
        {
            get
            {
                return this.AdditionalMessagesField;
            }
            set
            {
                this.AdditionalMessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientIdentifier
        {
            get
            {
                return this.ClientIdentifierField;
            }
            set
            {
                this.ClientIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientTypeId
        {
            get
            {
                return this.ClientTypeIdField;
            }
            set
            {
                this.ClientTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contract
        {
            get
            {
                return this.ContractField;
            }
            set
            {
                this.ContractField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailClient
        {
            get
            {
                return this.EmailClientField;
            }
            set
            {
                this.EmailClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailFP
        {
            get
            {
                return this.EmailFPField;
            }
            set
            {
                this.EmailFPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileClient
        {
            get
            {
                return this.MobileClientField;
            }
            set
            {
                this.MobileClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileFP
        {
            get
            {
                return this.MobileFPField;
            }
            set
            {
                this.MobileFPField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", ConfigurationName="Notifications.WSFSOC.NotificationsAppServiceContract")]
    public interface NotificationsAppServiceContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://oldmutual.com/soc/services/2015/12/INotificationsAppServiceContract/SendNo" +
            "tification", ReplyAction="http://oldmutual.com/soc/services/2015/12/NotificationsAppServiceContract/SendNot" +
            "ificationResponse")]
        System.Threading.Tasks.Task<Notifications.WSFSOC.SendNotificationResponse> SendNotificationAsync(Notifications.WSFSOC.SendNotificationRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://oldmutual.com/soc/services/2015/12/INotificationsAppServiceContract/GetNot" +
            "ificationResponse", ReplyAction="http://oldmutual.com/soc/services/2015/12/NotificationsAppServiceContract/GetNoti" +
            "ficationByOpetionResponse")]
        System.Threading.Tasks.Task<Notifications.WSFSOC.GetNotificationResponse> GetNotificationByOpetionAsync(Notifications.WSFSOC.GetNotificationRequets request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://oldmutual.com/soc/services/2015/12/INotificationsAppServiceContract/SendNo" +
            "tification_Template", ReplyAction="http://oldmutual.com/soc/services/2015/12/NotificationsAppServiceContract/SendNot" +
            "ification_TemplateResponse")]
        System.Threading.Tasks.Task<Notifications.WSFSOC.SendNotificationResponse> SendNotification_TemplateAsync(Notifications.WSFSOC.SendNotificationRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://oldmutual.com/soc/services/2015/12/INotificationsAppServiceContract/GetNot" +
            "ificationDetaillResponse", ReplyAction="http://oldmutual.com/soc/services/2015/12/NotificationsAppServiceContract/GetNoti" +
            "ficationByOpetionDetaillResponse")]
        System.Threading.Tasks.Task<Notifications.WSFSOC.GetNotificationDetaillResponse> GetNotificationByOpetionDetaillAsync(Notifications.WSFSOC.GetNotificationRequets request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://oldmutual.com/soc/services/2015/12/INotificationsAppServiceContract/SendNo" +
            "tificationDistList", ReplyAction="http://oldmutual.com/soc/services/2015/12/NotificationsAppServiceContract/SendNot" +
            "ificationDistListResponse")]
        System.Threading.Tasks.Task<Notifications.WSFSOC.SendNotificationDistListResponse> SendNotificationDistListAsync(Notifications.WSFSOC.SendNotificationDistListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://oldmutual.com/soc/services/2015/12/INotificationsAppServiceContract/SendNo" +
            "tificationDistListN", ReplyAction="http://oldmutual.com/soc/services/2015/12/NotificationsAppServiceContract/SendNot" +
            "ificationDistListNResponse")]
        System.Threading.Tasks.Task<Notifications.WSFSOC.SendNotificationDistListResponse> SendNotificationDistListNAsync(Notifications.WSFSOC.SendNotificationDistListNRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendNotificationRequest", WrapperNamespace="http://oldmutual.com/soc/services/2015/12", IsWrapped=true)]
    public partial class SendNotificationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=0)]
        public Notifications.WSFSOC.ContextBusiness ContextBusiness;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=1)]
        public int Plantilla;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=2)]
        public Notifications.WSFSOC.SendParameters SendParameters;
        
        public SendNotificationRequest()
        {
        }
        
        public SendNotificationRequest(Notifications.WSFSOC.ContextBusiness ContextBusiness, int Plantilla, Notifications.WSFSOC.SendParameters SendParameters)
        {
            this.ContextBusiness = ContextBusiness;
            this.Plantilla = Plantilla;
            this.SendParameters = SendParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendNotificationResponse", WrapperNamespace="http://oldmutual.com/soc/services/2015/12", IsWrapped=true)]
    public partial class SendNotificationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=0)]
        public Notifications.WSFSOC.OperationResult Result;
        
        public SendNotificationResponse()
        {
        }
        
        public SendNotificationResponse(Notifications.WSFSOC.OperationResult Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNotificationRequets", WrapperNamespace="http://oldmutual.com/soc/services/2015/12", IsWrapped=true)]
    public partial class GetNotificationRequets
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=0)]
        public string not_RFC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=1)]
        public string not_aplicacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=2)]
        public string not_contrato;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=3)]
        public System.DateTime not_fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=4)]
        public int not_plantilla;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=5)]
        public string not_proceso;
        
        public GetNotificationRequets()
        {
        }
        
        public GetNotificationRequets(string not_RFC, string not_aplicacion, string not_contrato, System.DateTime not_fecha, int not_plantilla, string not_proceso)
        {
            this.not_RFC = not_RFC;
            this.not_aplicacion = not_aplicacion;
            this.not_contrato = not_contrato;
            this.not_fecha = not_fecha;
            this.not_plantilla = not_plantilla;
            this.not_proceso = not_proceso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNotificationResponse", WrapperNamespace="http://oldmutual.com/soc/services/2015/12", IsWrapped=true)]
    public partial class GetNotificationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=0)]
        public Notifications.WSFSOC.ContextBusiness[] ContextBusiness;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=1)]
        public Notifications.WSFSOC.OperationResult Result;
        
        public GetNotificationResponse()
        {
        }
        
        public GetNotificationResponse(Notifications.WSFSOC.ContextBusiness[] ContextBusiness, Notifications.WSFSOC.OperationResult Result)
        {
            this.ContextBusiness = ContextBusiness;
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNotificationDetaillResponse", WrapperNamespace="http://oldmutual.com/soc/services/2015/12", IsWrapped=true)]
    public partial class GetNotificationDetaillResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=0)]
        public Notifications.WSFSOC.OperationResult Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=1)]
        public Notifications.WSFSOC.SendParameters[] SendParameters;
        
        public GetNotificationDetaillResponse()
        {
        }
        
        public GetNotificationDetaillResponse(Notifications.WSFSOC.OperationResult Result, Notifications.WSFSOC.SendParameters[] SendParameters)
        {
            this.Result = Result;
            this.SendParameters = SendParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendNotificationDistListRequest", WrapperNamespace="http://oldmutual.com/soc/services/2015/12", IsWrapped=true)]
    public partial class SendNotificationDistListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=0)]
        public Notifications.WSFSOC.ContextBusiness ContextBusiness;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=1)]
        public string[] LstEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=2)]
        public int Plantilla;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=3)]
        public Notifications.WSFSOC.SendParameters SendParameters;
        
        public SendNotificationDistListRequest()
        {
        }
        
        public SendNotificationDistListRequest(Notifications.WSFSOC.ContextBusiness ContextBusiness, string[] LstEmail, int Plantilla, Notifications.WSFSOC.SendParameters SendParameters)
        {
            this.ContextBusiness = ContextBusiness;
            this.LstEmail = LstEmail;
            this.Plantilla = Plantilla;
            this.SendParameters = SendParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendNotificationDistListResponse", WrapperNamespace="http://oldmutual.com/soc/services/2015/12", IsWrapped=true)]
    public partial class SendNotificationDistListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=0)]
        public Notifications.WSFSOC.OperationResult Result;
        
        public SendNotificationDistListResponse()
        {
        }
        
        public SendNotificationDistListResponse(Notifications.WSFSOC.OperationResult Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendNotificationDistListNRequest", WrapperNamespace="http://oldmutual.com/soc/services/2015/12", IsWrapped=true)]
    public partial class SendNotificationDistListNRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=0)]
        public Notifications.WSFSOC.ContextBusinessN ContextBusinessN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=1)]
        public string[] LstEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=2)]
        public Notifications.WSFSOC.NotificationTemplateN Plantilla;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://oldmutual.com/soc/services/2015/12", Order=3)]
        public Notifications.WSFSOC.SendParametersN SendParametersN;
        
        public SendNotificationDistListNRequest()
        {
        }
        
        public SendNotificationDistListNRequest(Notifications.WSFSOC.ContextBusinessN ContextBusinessN, string[] LstEmail, Notifications.WSFSOC.NotificationTemplateN Plantilla, Notifications.WSFSOC.SendParametersN SendParametersN)
        {
            this.ContextBusinessN = ContextBusinessN;
            this.LstEmail = LstEmail;
            this.Plantilla = Plantilla;
            this.SendParametersN = SendParametersN;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface NotificationsAppServiceContractChannel : Notifications.WSFSOC.NotificationsAppServiceContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class NotificationsAppServiceContractClient : System.ServiceModel.ClientBase<Notifications.WSFSOC.NotificationsAppServiceContract>, Notifications.WSFSOC.NotificationsAppServiceContract
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NotificationsAppServiceContractClient() : 
                base(NotificationsAppServiceContractClient.GetDefaultBinding(), NotificationsAppServiceContractClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NotificationsAppServiceEndpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationsAppServiceContractClient(EndpointConfiguration endpointConfiguration) : 
                base(NotificationsAppServiceContractClient.GetBindingForEndpoint(endpointConfiguration), NotificationsAppServiceContractClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationsAppServiceContractClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NotificationsAppServiceContractClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationsAppServiceContractClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NotificationsAppServiceContractClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationsAppServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Notifications.WSFSOC.SendNotificationResponse> Notifications.WSFSOC.NotificationsAppServiceContract.SendNotificationAsync(Notifications.WSFSOC.SendNotificationRequest request)
        {
            return base.Channel.SendNotificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Notifications.WSFSOC.SendNotificationResponse> SendNotificationAsync(Notifications.WSFSOC.ContextBusiness ContextBusiness, int Plantilla, Notifications.WSFSOC.SendParameters SendParameters)
        {
            Notifications.WSFSOC.SendNotificationRequest inValue = new Notifications.WSFSOC.SendNotificationRequest();
            inValue.ContextBusiness = ContextBusiness;
            inValue.Plantilla = Plantilla;
            inValue.SendParameters = SendParameters;
            return ((Notifications.WSFSOC.NotificationsAppServiceContract)(this)).SendNotificationAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<Notifications.WSFSOC.GetNotificationResponse> GetNotificationByOpetionAsync(Notifications.WSFSOC.GetNotificationRequets request)
        {
            return base.Channel.GetNotificationByOpetionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Notifications.WSFSOC.SendNotificationResponse> Notifications.WSFSOC.NotificationsAppServiceContract.SendNotification_TemplateAsync(Notifications.WSFSOC.SendNotificationRequest request)
        {
            return base.Channel.SendNotification_TemplateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Notifications.WSFSOC.SendNotificationResponse> SendNotification_TemplateAsync(Notifications.WSFSOC.ContextBusiness ContextBusiness, int Plantilla, Notifications.WSFSOC.SendParameters SendParameters)
        {
            Notifications.WSFSOC.SendNotificationRequest inValue = new Notifications.WSFSOC.SendNotificationRequest();
            inValue.ContextBusiness = ContextBusiness;
            inValue.Plantilla = Plantilla;
            inValue.SendParameters = SendParameters;
            return ((Notifications.WSFSOC.NotificationsAppServiceContract)(this)).SendNotification_TemplateAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<Notifications.WSFSOC.GetNotificationDetaillResponse> GetNotificationByOpetionDetaillAsync(Notifications.WSFSOC.GetNotificationRequets request)
        {
            return base.Channel.GetNotificationByOpetionDetaillAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Notifications.WSFSOC.SendNotificationDistListResponse> Notifications.WSFSOC.NotificationsAppServiceContract.SendNotificationDistListAsync(Notifications.WSFSOC.SendNotificationDistListRequest request)
        {
            return base.Channel.SendNotificationDistListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Notifications.WSFSOC.SendNotificationDistListResponse> SendNotificationDistListAsync(Notifications.WSFSOC.ContextBusiness ContextBusiness, string[] LstEmail, int Plantilla, Notifications.WSFSOC.SendParameters SendParameters)
        {
            Notifications.WSFSOC.SendNotificationDistListRequest inValue = new Notifications.WSFSOC.SendNotificationDistListRequest();
            inValue.ContextBusiness = ContextBusiness;
            inValue.LstEmail = LstEmail;
            inValue.Plantilla = Plantilla;
            inValue.SendParameters = SendParameters;
            return ((Notifications.WSFSOC.NotificationsAppServiceContract)(this)).SendNotificationDistListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Notifications.WSFSOC.SendNotificationDistListResponse> Notifications.WSFSOC.NotificationsAppServiceContract.SendNotificationDistListNAsync(Notifications.WSFSOC.SendNotificationDistListNRequest request)
        {
            return base.Channel.SendNotificationDistListNAsync(request);
        }
        
        public System.Threading.Tasks.Task<Notifications.WSFSOC.SendNotificationDistListResponse> SendNotificationDistListNAsync(Notifications.WSFSOC.ContextBusinessN ContextBusinessN, string[] LstEmail, Notifications.WSFSOC.NotificationTemplateN Plantilla, Notifications.WSFSOC.SendParametersN SendParametersN)
        {
            Notifications.WSFSOC.SendNotificationDistListNRequest inValue = new Notifications.WSFSOC.SendNotificationDistListNRequest();
            inValue.ContextBusinessN = ContextBusinessN;
            inValue.LstEmail = LstEmail;
            inValue.Plantilla = Plantilla;
            inValue.SendParametersN = SendParametersN;
            return ((Notifications.WSFSOC.NotificationsAppServiceContract)(this)).SendNotificationDistListNAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NotificationsAppServiceEndpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NotificationsAppServiceEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://10.42.1.67/WSFSOC/NotificationsAppService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NotificationsAppServiceContractClient.GetBindingForEndpoint(EndpointConfiguration.NotificationsAppServiceEndpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NotificationsAppServiceContractClient.GetEndpointAddress(EndpointConfiguration.NotificationsAppServiceEndpoint);
        }
        
        public enum EndpointConfiguration
        {
            
            NotificationsAppServiceEndpoint,
        }
    }
}
